### ISSUE TITLE
Add SAML auth for login

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/ol-customizations-nytimes-library#4]
# User Story

- As a stakeholder for MIT Open, I want to be able to access the project documentation with a familiar login
- As a product owner for MIT Open, I want to reduce friction for stakeholders accessing project documentation

# Description/Context
The NYTimes Library app uses the [Passport.JS](http://www.passportjs.org/) library to manage authentication. We would like to update this customization repo to use the [passport-saml](https://github.com/node-saml/passport-saml) strategy so that we can use Touchstone login for this documentation site. There is an example repository that uses that library that we can use as a reference [here](https://github.com/gbraad/passport-saml-example/)

# Acceptance Criteria

- [x] The site at https://mitopen-docs.odl.mit.edu uses Touchstone SAML as the login method

**Comment by JenniWhitman** [comment]
We have auth almost working in RC - just working on getting the profile attributes correctly mapped. Once that's complete, we'll push to production.

**Comment by shaidar** [comment]
Quick update from @JenniWhitman: https://mitopen-docs-rc.odl.mit.edu/ I've not only got it getting me to the app after, but also have errors/xml output in logs so I'll just work out the profile issue rq and we're good!

Crux of the issue is:
https://github.com/node-saml/passport-saml/issues/128#issuecomment-435304470

**Comment by shaidar** [comment]
Jenni got SAML auth figured out and the profile mapped on RC. She also made a change that allows the metadata endpoint be accessible even while using the google auth strategy which would allow to request that IST register the production app without disrupting the service.

While Jenni works on squashing the merges and cleaning up the code, i'm gonna deploy the changes to production and request IST register the app. Once that takes place, which should be sometime today, we'll switch the production app to using SAML auth and would be all set.

**Comment by JenniWhitman** [comment]
Update: RC is fully functional. For the time being, I've made it so while in another strategy metadata can still be built in prod. I am going to open a series of issues as a result of this work:
- There is a 500 on logout, but you still get logged out. Since it is functional, just not pretty, putting in an issue to fix soon.
- There is code in the library repo that can and should be refactored out to this repo. We had issues getting it to work at the start (at all), but it is worth us going back and refactoring out.  Would also be nice to try and push this upstream to save others headache.

Sar has passed off the info to IS&T for certs for prod, so once we get those, all will be up and running.  At that time, I will take out the code that is allowing metadata when not in google or slack.

**Comment by JenniWhitman** [comment]
Added:
https://github.com/mitodl/ol-customizations-nytimes-library/issues/8 - get-started link
https://github.com/mitodl/library/issues/17 - 500 on logout
https://github.com/mitodl/library/issues/18 - refactor

**Comment by shaidar** [comment]
Production app has now been registered with the SAML IDP. Will give it thirty minutes or so to make sure all's set on that end and switch the `OAUTH_STRATEGY` to saml on the prod app.

**Comment by shaidar** [comment]
Production app is now using SAML auth and I was able to successfully log in.
